"""add github and dailycomment

Revision ID: 373e9c4287e7
Revises: f8a96c17df99
Create Date: 2020-07-26 18:10:46.648099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373e9c4287e7'
down_revision = 'f8a96c17df99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_github',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('date', sa.Date(), nullable=True, comment='日期'),
    sa.Column('url', sa.String(length=150), nullable=True, comment='链接'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('language', sa.String(length=100), nullable=True, comment='语言'),
    sa.Column('stars', sa.Integer(), nullable=True, comment='星'),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('currentPeriodStars', sa.Integer(), nullable=True, comment='最近的星'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_daily_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('body', sa.Text(), nullable=False, comment='内容'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='关联对象'),
    sa.ForeignKeyConstraint(['author_id'], ['tb_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_daily_comment_author_id'), 'tb_daily_comment', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_daily_comment_author_id'), table_name='tb_daily_comment')
    op.drop_table('tb_daily_comment')
    op.drop_table('tb_github')
    # ### end Alembic commands ###
