"""change bill,add type

Revision ID: a2dc7b7dd181
Revises: 373e9c4287e7
Create Date: 2020-08-16 14:02:55.303589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dc7b7dd181'
down_revision = '373e9c4287e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_consumption_type_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consumption_type', sa.String(length=100), nullable=True),
    sa.Column('mark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tb_bill', sa.Column('consumption_type_id', sa.Integer(), nullable=True, comment='关联消费类型字典表'))
    op.add_column('tb_bill', sa.Column('mark', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tb_bill_consumption_type_id'), 'tb_bill', ['consumption_type_id'], unique=False)
    op.create_foreign_key(None, 'tb_bill', 'tb_consumption_type_dict', ['consumption_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_bill', type_='foreignkey')
    op.drop_index(op.f('ix_tb_bill_consumption_type_id'), table_name='tb_bill')
    op.drop_column('tb_bill', 'mark')
    op.drop_column('tb_bill', 'consumption_type_id')
    op.drop_table('tb_consumption_type_dict')
    # ### end Alembic commands ###
