"""Initial migration.

Revision ID: f8a96c17df99
Revises: 
Create Date: 2020-07-26 18:01:33.131508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a96c17df99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录日期'),
    sa.Column('last_ip', sa.String(length=16), nullable=True, comment='最后登录日期'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payfor', sa.String(length=255), nullable=True, comment='消费对象'),
    sa.Column('money', sa.Float(), nullable=True, comment='消费金额'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='关联对象'),
    sa.Column('status', sa.String(length=1), nullable=True, comment='状态'),
    sa.Column('datetime', sa.DateTime(), nullable=True, comment='日期时间'),
    sa.ForeignKeyConstraint(['author_id'], ['tb_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_bill_author_id'), 'tb_bill', ['author_id'], unique=False)
    op.create_table('tb_todolist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False, comment='内容'),
    sa.Column('date', sa.Date(), nullable=True, comment='日期'),
    sa.Column('done', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='关联对象'),
    sa.ForeignKeyConstraint(['author_id'], ['tb_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_todolist_author_id'), 'tb_todolist', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_todolist_author_id'), table_name='tb_todolist')
    op.drop_table('tb_todolist')
    op.drop_index(op.f('ix_tb_bill_author_id'), table_name='tb_bill')
    op.drop_table('tb_bill')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
